export {default as HomePage} from "./HomePage"
export {default as NavBar} from "./NavBar"
export {default as Projects} from "./Projects"
export {default as Contact} from "./Contact"
export {default as AboutMe} from "./AboutMe"
export {default as Reveal} from "./Reveal"
export {default as ProductReveal} from "./ProductReveal"